server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://userServer
          predicates:
            - Path=/user/**
        - id: order-service
          uri: lb://orderServer
          predicates:
            - Path=/order/**













